### ISSUE TITLE
Relationships returning null.

### ISSUE THREAD

**Issue by PZ01** [nuwave/lighthouse-example#1]
I used lighthouse in my own project, but I couldn't get the eloquent relationship directives to work. I am running this example project and I am encountering the same problem.

The only change I made in the lighthouse-example project is that I used the resolver for the jobs list in the schema.graphql file.
![2](https://user-images.githubusercontent.com/6424653/39069478-db843480-44ad-11e8-886e-15d5a5465256.png)
![1](https://user-images.githubusercontent.com/6424653/39069479-db96d2fc-44ad-11e8-94a0-7c440008d12b.png)

I have no issues querying the Models through tinker with their relationships. I can supply more information. I'm going to investigate this, but I wonder if other people have had this issue before.

I did a DB::Listen to log the output of the sql statements, I'll attach the file for a single call to the graphql call pictured above.
[laravel.log](https://github.com/nuwave/lighthouse-example/files/1933404/laravel.log)

**Comment by chrissm79** [comment]
Hey @PZ01, could you post what your field resolver looks like? Also, can you post all of your schema file(s)? I cloned the repo, ran the seeder, used the `Query@jobs` field resolver and was able to query the `belongsTo` relationship with the following output:

<img width="1288" alt="screen shot 2018-04-22 at 4 43 15 pm" src="https://user-images.githubusercontent.com/1976169/39101321-daeb4cde-464c-11e8-954d-7b10954ee714.png">

```graphql
type User {
  name: String!
  email: String!
  jobs: [Job!]! @hasMany
}

type Job {
  title: String!
  user: User @belongsTo
  tasks: [Task!]! @hasMany(type: "paginator")
}

type Query {
  me: User @auth
  jobs: [Job!]! @field(resolver: "App\\Http\\GraphQL\\Query@jobs")
}
```

**Comment by chrissm79** [comment]
@PZ01 Also, are you using MySQL or a different DB?

**Comment by PZ01** [comment]
@chrissm79 thanks for your prompt answer. I was using the default sqlite connection, but I suppose some sql instructions are not supported, I switched to a local MySQL database and it is working now.

That being said, for my own project I use Amazon RDS and I get the problem with the relationships returning null. I will try this week to use this example project to connect to my RDS instance and create two models to test this use case. The amazon instance is using the Aurora MySQL 5.6.10a engine.

**Comment by chrissm79** [comment]
@PZ01 The relationship helpers have only been tested on MySQL and required a [query builder](https://github.com/nuwave/lighthouse/blob/master/src/Support/DataLoader/QueryBuilder.php) to get around the N+1 issue. Aurora says it fully supports MySQL (if you choose that version) so I'm disappointed to hear that it's not working. When I have some time I'll see if I can test the relations out on Postgres/Sqlite/Aurora. 

But to be completely upfront, I'm not sure when that will be. I'll create an issue on the main repo to keep track of the status but let me know if you confirm that Aurora is/isn't working. Thanks!!
